### ISSUE TITLE
Feature request: Generate models for Archetype

### ISSUE THREAD

**Issue by jbreuer** [zpqrtbnk/Zbu.ModelsBuilder#13]
This is a rather strange feature request and I'm just thinking out loud here, but it would be nice if the models builder couldn't just generate models and properties based on document types, but also on configured [Archetype](http://imulus.github.io/Archetype/) datatypes. 

I use Archetype more and more and if an Archetype datatype is added to a document type the models builder generates the following property:

```
[ImplementPropertyType("slider")]
public ArchetypeModel Slider
{
    get { return this.GetPropertyValue<ArchetypeModel>("slider"); }
}
```

This is the slider datatype:
![slider](https://cloud.githubusercontent.com/assets/5444597/3977867/f67752ba-283f-11e4-9253-8bee27a2a635.jpg)
This is the slider on a node:
![slider2](https://cloud.githubusercontent.com/assets/5444597/3977881/219fa5b4-2840-11e4-9460-81dbae0822f3.jpg)
I always need to overwrite those generated properties in a partal class so it will return the data in a better format.

```
public partial class Home
{
    [ImplementPropertyType("slider")]
    public IEnumerable<Slider> Slider
    {
        get
        {
            var archetypeModel = this.GetPropertyValue<ArchetypeModel>("slider");
            return archetypeModel.Select(x =>
                {
                    return new Slider()
                    {
                        Title = x.GetValue<string>("title"),
                        Text = x.GetValue<IHtmlString>("text"),
                        Image = x.GetValue<Image>("image")
                    };
                }
            ).ToList();
        }
    }
}
public class Slider
{
    public string Title { get; set; }
    public IHtmlString Text { get; set; }
    public Image Image { get; set; }
}
```

As you can see I still need to do things like x.GetValue<IHtmlString>("text") and x.GetValue<Image>("image") which are the Archetype equivalent of Model.Content.GetPropertyValue<>("") and it also goes through the Property Editor Value Converters.

So the more I use Archetype the more I still need to programm my own properties while in theory a model could also be generated from the Slider Archetype datatype because it's kind of like a document type. It has datatypes which could be converted to properties on a model.

I wonder if something like this is possible :-).

**Comment by hfloyd** [comment]
+1 for "also generate models for the grid editor" :-)

**Comment by MrMattTaylor** [comment]
I was just looking at the Grid Layout myself and hoping the model builder would work with it.
I'm guessing it may be some time off.

**Comment by Lechus** [comment]
+1 Grid editor in u7.2

**Comment by hfloyd** [comment]
Regarding the Grid... I found that the ['Skybrud.Umbraco.GridData'](https://github.com/skybrud/Skybrud.Umbraco.GridData) library works well. 

It really isn't very much work to override those Grid properties in the customized partial class:
	
		using Skybrud.Umbraco.GridData;
	    using Umbraco.Web;
	    using Zbu.ModelsBuilder;
	
	    /// <summary>
	    /// The text page.
	    /// </summary>
	    public partial class TextPage
	    {
	        /// <summary>
	        /// Gets the page body text as a grid object
	        /// </summary>
	        [ImplementPropertyType("PageBodyText")]
	        public GridDataModel PageBodyText
	        {
	            get
	            {
	                return this.GetPropertyValue<GridDataModel>("PageBodyText");
	            }
	        }
	    }

**Comment by micklaw** [comment]
Hey Folks,

I know this is an old post, but I noticed some nice changes in the Ditto develop branch which make implementing POCO Archetypes, or whatever really for that matter, quite easy. I created a quick repo (https://github.com/micklaw/Ditto.Resolvers) PoC today which shows using POCOs for Archetypes and Nested Archetypes via Ditto.

This does currently only hang from the develop branch of Ditto, so is not practical for use just now, but hopefully when or if those changes are merged in it should start working or be a good started for implementation.

Cheers

**Comment by kgiszewski** [comment]
I'm late to the Ditto party, but will be testing the main package soon so I can formulate an intelligent response to this :)

**Comment by zpqrtbnk** [comment]
Planning to discuss the whole modeling thing with co-modelers at CG15!

**Comment by kgiszewski** [comment]
I'll stay tuned :)

**Comment by kgiszewski** [comment]
@micklaw Thanks for posting that repo for making Ditto and Archetype work together.  However it's not clear to me what your code does.  Meaning if I just create a POCO like so:
```
using Archetype.Models;
using Umbraco.Core.Models.PublishedContent;

namespace MendozaApp.UmbracoExtensions.Wiki.Models
{
    public class WikiTopicModel : PublishedContentModel
    {
        public WikiTopicModel(Umbraco.Core.Models.IPublishedContent content) : base(content) { }

        public string Content { get; set; }

        public ArchetypeModel QuickLinks { get; set; }
    }
}
```

I'm then able to access the model on the template like the following without using any additional code:
```
var pageModel = Model.Content.As<WikiTopicModel>();

@foreach (var x in pageModel.QuickLinks)
{
        <div>@x.GetValue("someProperty")</div>

}
```

Does your code map the Archetype properties as well to a model?

Sorry for the questions.

**Comment by micklaw** [comment]
Don't be sorry, I haven't exactly written pages of docs =)

Yeah, that's the idea. There's a brief explanation on the read me on the GitHub page. Basically there will be a POCO for your DocType (Ditto) and also a POCO for your Archetype. 

To bind an Archetype on your DocType class you will create a public property and decorate that with an Attribute:

  [ArchetypeResolver("DifferentPropertyName")]
    public List<CustomArchetype> List { get; set; }

CustomArchetype in this instance would be your Archetype POCO and its fields would map to the properties you have created in your Archetype. As long as CustomArchetype inherits from ArchetypeFieldsetModel and it has the same name as the fieldset alias in the datatype it should just work.

I'll knock up an example when the kids are asleep. Couldn't do it one handed ;)

**Comment by kgiszewski** [comment]
Ok sounds good. Not sure if @zpqrtbnk wants this thread to continue on his project, but thanks for looking into this.

**Comment by micklaw** [comment]
@kgiszewski I've added a sample project to the solution to show how this works, hopefully it gives the gist. I think your right, this chat should probably be moved to the new repository so were not spamming. Anything else you want to know just add as a Issue on https://github.com/micklaw/Ditto.Resolvers and i'll get back to you asap. I'll also get cracking on some docs.

**Comment by zpqrtbnk** [comment]
@kgiszewski I'm happy having this thread here ;-) But if you think of a more appropriate place, just move it there and post the link here. It's a cross-solutions discussion anyway.

Highly interesting to me though, because:

* **Models generation and caching.** With the (currently experimental) NuCache, the actual IPublishedContent objects will be cached (and not recreated from Xml all the time). And if the models factory is used, it's the *model* itself that is cached. Brings flexibility and performance, but requires a clarification of what can be done, and what cannot, with models.

* **Nested/Detached/Virtual/YouNameIt content.** At the moment Core is focused on IPublishedContent -- our own, those that we manage, those that are *nodes* in the database and have an ID, etc. But with Archetype, the Grid, and other projects, it becomes obvious that solutions should exist for a somewhat unified way of dealing with content, whether it's a "true node" or only a "part" of a true node.

**Comment by LoganPeck** [comment]
Hi guys, on the subject of Archetype & Models Builder working nicely together, I have put together a little add-on that takes care of it on data type save. It will create a strongly typed model (cs file) based off of the Archetype prevalues. It also overrides the ArchetypeValueConverter so Archetype can tell the Models Binder what Type to expect. https://github.com/LoganPeck/Umbraco-Archetype-Model-Binder-Add-On

This is my first time contributing code anywhere so my documentation/coding style may be off. Feel free to check it out and let me know if there are any suggestions or questions. Also feel free to contribute as well!

**Comment by hfloyd** [comment]
For those of you using Archetype with ModelsBuilder, you might consider trying the "Nested Content" package. It is just as quick and easy to create "custom" datatypes as using Archetype. And since Nested Content uses Doctypes as the "blueprints", and ModelsBuilder uses Doctypes, it's easy to have a model generated for the properties defined on a Nested Content automatically.

An example scenario:

The Doctype "Homepage" has a NestedContent of type "ResourceBox" (which has some properties: Title, Description, Link, Image, etc.)

By default, ModelsBuilder will create a model for ResourceBox, since it is defined as a DocType, and just like for other Doctypes, we can create a custom partial to add or change the way properties are returned.

The "HompageResourceBoxes" property on the "Homepage" model is generated automatically as:

	/// <summary>Resource Boxes</summary>
	[ImplementPropertyType("HomepageResourceBoxes")]
	public object HomepageResourceBoxes
	{
		get { return this.GetPropertyValue("HomepageResourceBoxes"); }
	}

So, we override that with a custom property implementation:

	/// <summary>Resource Boxes</summary>
    [ImplementPropertyType("HomepageResourceBoxes")]
    public IEnumerable<ResourceBox> HomepageResourceBoxes
    {
        get
        {
            var items = this.GetPropertyValue<IEnumerable<IPublishedContent>>("HomepageResourceBoxes");
            return items.ToResourceBoxes();
        }
    }

	...

	public static IEnumerable<ResourceBox> ToResourceBoxes(this  IEnumerable<IPublishedContent> Content)
	{
	    var list = new List<ResourceBox>();
	
	    foreach (var item in Content)
	    {
	        var rb = new ResourceBox(item);
	        list.Add(rb);
	    }
	
	    return list;
	}


Now you can access these strongly-typed in a view like:

	@if (Model.Content.HomepageResourceBoxes.Any())
	{
	    foreach (var box in Model.Content.HomepageResourceBoxes)
	    {
	        <div class="resourceitem">
                <p><a href="@box.Link.Url">@box.ResourceBoxTitle</a></p>
                @Html.Raw(box.Description)                
	        </div>
	    }
	}

Just an alternative to consider.

**Comment by jbreuer** [comment]
Thanks for the advice. I've also switched to Nested Content and it works really great! https://gist.github.com/jbreuer/0a5996e5e6bf881ce847

**Comment by zpqrtbnk** [comment]
Quick comment: I don't think the ModelsBuilder will be able to "generate" models for Archetype anytime soon. The good thing with packages such as NestedContent is that they rely on the already-existing content type system, and therefore can have models easily generated.

Next step is to add a way so that we can easily figure out the model type that would be returned by a nested content property. Which, I think, is feasible. There might be a way to generate the `IEnumerable<ResourceBox>` above directly. Work-in-progress...

**Comment by hfloyd** [comment]
That would be great, Stephan! I don't use so many NC properties that the customizing work is too much for me, but those who do use them heavily would certainly benefit from a helping hand :-)

**Comment by navid-dada** [comment]
please add this feature....
