### ISSUE TITLE
Custom Tool password format throws [Unauthorized] error

### ISSUE THREAD

**Issue by FDBenevides** [zpqrtbnk/Zbu.ModelsBuilder#154]
Hi guys,

I've been trying to find the issue for about 2hours....and I think I've found out!
I had setup my VS(2015) solution, Umbraco libs (7.6.6) and ModelsBuilder (3.0.6 and 3.0.7) like I did before but when I tried to run the ModelsBuilder custom tool it always return [Unauthorized]. I've checked URL, Username and Password so many times and they were all Ok.
After back and forth with nuget versions and always the same error, I decided to create a new user with name/password "modelsbuilder/modelsbuilder" and it worked! 

Then I changed the modelsbuilder user password to the same I was trying before...and the [Unauthorized] error began! My password is like ":H------P-------2017!" with the '-' being smallcase letters. 

I don't know if it's related with the length but please (at least) put it in the wiki section ^^

Regards

**Comment by zpqrtbnk** [comment]
W.T.F. ? ;-) so you're saying that using this very specific password breaks the auth? Well that is amazing and... aaaaaaarhhh. Bug indeed. Will fix.

Details: so far, MB uses basic auth (sends user and password) because you're supposed to use it locally. Meaning we send, exactly, "<user>:<password>". And then in `ApiBasicAuthFilter` we split at ':' - but... because your password contains ':', and my code has flaws, it fails. Easy to fix, will.

**Comment by FDBenevides** [comment]
Good to hear :D
At least it can be easily fixed.

Thank you very much ;)
Good work

**Comment by zpqrtbnk** [comment]
Fixed in source, will need a new release.
