### ISSUE TITLE
Interface property discarded when moving property from generated class to custom partial class

### ISSUE THREAD

**Issue by netaddicts** [zpqrtbnk/Zbu.ModelsBuilder#155]
Ran into this today, and wondering if this is intended behaviour or to be considered bad practice or bug

Declared a composition "Composition" with a single text string property
Declared a doc type "Composed" using composition "Composition", added an extra text string property onto this document type.

Generating models results in interface declaration IComposition with single property and class Composed implementing IComposition interface

Right after that, I'm moving the interface implementation of the composition property to a custom partial class "Composition" because I need to perform some extra code (out of scope here)

```
	public partial class Composition
	{
		///<summary>
		/// Property
		///</summary>
		[ImplementPropertyType("property")]
		public string Property
		{
			get { return GetProperty(this); }
		}

		/// <summary>Static getter for Property</summary>
		public static string GetProperty(IComposition that) { return that.GetPropertyValue<string>("property"); }
	}
```

I regenerate the models which results in an empty interface declaration

```
	// Mixin content Type 1064 with alias "composition"
	/// <summary>Composition</summary>
	public partial interface IComposition : IPublishedContent
	{
	}
```

Expected to still see the property declaration in the interface.

Thoughts?
Can I work around this behaviour? Bug? By design?

--Dirk

**Comment by zpqrtbnk** [comment]
We detect that you have provided your own implementation of the property, and therefore assume you are taking care of everything, i.e. both the interface declaration and the implementation. We're unfortunately not clever enough to figure out that you have *not* provided the interface declaration. So it would be "by design", but a design that I know is slightly flawed.

There is an ongoing evolution of MB that would have finer granularity, alas I'm focussing on v8 at the moment.

So... I'm not sure you can work around the behavior, other than by also providing the interface declaration.

Bit frustrating, but probably the best I can do right now.

Making sense?

**Comment by netaddicts** [comment]
Ok, I'm going to give this a try, and add the partial interface declaration, didn't think of that yet, so good suggestion.

Yes, answer makes sense and is satisfying

**Comment by netaddicts** [comment]
Adding a custom partial interface with property declaration of property implemented in custom partial class works! :+1:
