### ISSUE TITLE
LanguageVersion cannot be higher than CSharp6

### ISSUE THREAD

**Issue by neoKushan** [zpqrtbnk/Zbu.ModelsBuilder#165]
We discovered an issue whereby ModeslBuilder fails to build when your Umbraco Project uses language features from CSharp7 or later. 

Although Umbraco itself works fine, syntax errors will occur because there's no way for ModelsBuilder to use a language version higher than CSharp6.

**Comment by zpqrtbnk** [comment]
This is due to the current version of Roslyn that ModelsBuilder relies upon. Need to upgrade at some point.

**Comment by ronaldbarendse** [comment]
This is probably only the case when using a ModelsMode that dynamically compiles the generated code (e.g. PureLive/Dll), because that will use the referenced `Microsoft.CodeAnalysis.CSharp` package instead of the built-in/system compiler.

Maybe try generating AppData models or just updating the `Microsoft.CodeAnalysis.CSharp` NuGet package to the latest version?

**Comment by zpqrtbnk** [comment]
The Roslyn version supported by MB in Umbraco 7 does not support CSharp greater than CSharp6. Supporting CSharp7 and above would require that we upgrade Roslyn. Which comes with its own set of problems. See discussion in #106.
