### ISSUE TITLE
Can't install custom tool visual studio 2019

### ISSUE THREAD

**Issue by FransdeJong** [zpqrtbnk/Zbu.ModelsBuilder#183]
The Custom tool needs a new max version to work in VS2019

**Comment by zpqrtbnk** [comment]
Done in source. See core task [4880](https://github.com/umbraco/Umbraco-CMS/issues/4880) for release.

**Comment by FransdeJong** [comment]
Thanks, I can install it but it won't run for Umbraco V7.
You (UmbracoHQ) really want us to switch to V8 right? :-P

**Comment by Alkaersig** [comment]
Think i will stick to using the options menu trick for a while then. Saw someone having the same problem on our:
https://our.umbraco.com/forum/extending-umbraco-and-using-the-api/96100-model-builder-auto-upgrade-to-v802

**Comment by FransdeJong** [comment]
Please share the "options menu trick".

**Comment by Alkaersig** [comment]
Sorry this was for the wrong issue. I'm waiting for the updated Custom Tool for the options to update correctly when switching solution. Not using 2019 yet, but subscribed to this issue as i was waiting for Custom Tool to support 2019 as well (since i would not upgrade to 2019 until it works as we are using it for quite a lot of projects).

**Comment by FransdeJong** [comment]
I build models in 2017 and code in 2019 now. Feels a bit strange but it works :-)
2019 runs so mutch better on my PC so this method beats working in 2017 for me.
