### ISSUE TITLE
UmbracoCms 8.0.0 constraint

### ISSUE THREAD

**Issue by tbraz** [zpqrtbnk/Zbu.ModelsBuilder#192]
Can't install Umbraco.ModelsBuilder.Ui 8.0.2 NuGET package because UmbracoCms 8.0.0 constraint to Umbraco.ModelsBuilder.Ui (= 8.0.1)

**Comment by zpqrtbnk** [comment]
Yes - twitted about it yesterday : although ModelsBuilder 8.0.2 has been released on NuGet and Visual Studio MarketPlace, it won't be usable before we release the next patch release of Umbraco (quite probably, 8.0.1) - because it requires fixes in Umbraco. So... it wouldn't even run on Umbraco 8.0.0.

Stay tuned ;-)

**Comment by tbraz** [comment]
My bad ... should follow you on twitter :P
