### ISSUE TITLE
Support for VS2019 / install

### ISSUE THREAD

**Issue by Alkaersig** [zpqrtbnk/Zbu.ModelsBuilder#204]
I can't seem to install the Custom Tool for Visual Studio 2019. According to #183 it has been bumped for 2019, but it does not seem to work.

Maybe it is related to v16.1 and requirements for extensions to be async loaded?
https://devblogs.microsoft.com/visualstudio/updates-to-synchronous-autoload-of-extensions-in-visual-studio-2019/

**Comment by zpqrtbnk** [comment]
I am not sure, and I am getting conflicting reports. I *think* it worked on the very first VS2019 releases, and something broke it at some point - when extensions were required to be async loaded indeed. Definitively an issue I need to fix (looking for time now).

**Comment by Sjoo90** [comment]
Hi @zpqrtbnk ,
What's the status in this issue, I only have VS2019 installed (after windows reinstall) and need this tool :)

**Comment by zpqrtbnk** [comment]
Commited to do it and maintain ModelsBuilder. 
Takes time.
Just sorting out the how and when at the moment.

**Comment by Matthew-Wise** [comment]
@Sjoo90 A work around that results in a the generated files been generated in the same location is to use:

```
 <add key="Umbraco.ModelsBuilder.Enable" value="true" />
        <add key="Umbraco.ModelsBuilder.ModelsMode" value="LiveAppData" />
        <add key="Umbraco.ModelsBuilder.AcceptUnsafeModelsDirectory" value="true" />
        <add key="Umbraco.ModelsBuilder.ModelsDirectory" value="{path to folder}" />  
```

Hope this helps you get under way again at least

**Comment by zpqrtbnk** [comment]
Related to these issues:
* #199 Custom tool hangs on VS2019
* #191 Warnings when uploading the VSIX to VisualStudio MarketPlace

Going to deal with them all as one issue - it's all due to Visual Studio package needing to be async now.

Here is [Umbraco.ModelsBuilder.CustomTool-8.0.5.vsix.zip](https://github.com/zpqrtbnk/Zbu.ModelsBuilder/files/3300117/Umbraco.ModelsBuilder.CustomTool-8.0.5.vsix.zip)
 which contains a VSIX which tries to address these issues. I have been able to install it and run in successfully on the latest VS2017, latest VS2019, and latest VS2019 preview. Could you please test and report?

If it's OK I'll upload it to the MarketPlace.

**Comment by zpqrtbnk** [comment]
Test VSIX has been reported to install and run - is now on VisualStudio MarketPlace.

Closing this issue, please open a new issue in case anything goes wrong.

And many thanks to our great testers!
