### ISSUE TITLE
Cannot find custom tool on this system

### ISSUE THREAD

**Issue by owlyowl** [zpqrtbnk/Zbu.ModelsBuilder#212]
I can verify the extension is installed. I've tried restarting my whole machine.

I've uninstalled and re-installed and it is still not working in vs 2019

**Comment by zpqrtbnk** [comment]
Hey - did it "solve itself"? or is this still a thing?

**Comment by owlyowl** [comment]
Hi! Error was between chair and keyboard I was reading your old docs and
stumbled upon the new ones with the .mb example

**Comment by croban** [comment]
I have same problem with visual studio extension. 
I am using visual studio 2017 and Umbraco 8.1.4.
This are web.config settings for Model Builder:

```<add key="Umbraco.ModelsBuilder.Enable" value="true" />
<add key="Umbraco.ModelsBuilder.ModelsMode" value="Nothing" />
<add key="Umbraco.ModelsBuilder.EnableApi" value="true" />
<add key="Umbraco.ModelsBuilder.LanguageVersion" value="CSharp7" />
<add key="Umbraco.ModelsBuilder.EnableFactory" value="true" />
<add key="Umbraco.ModelsBuilder.ModelsNamespace"  value="Core.Model.PublishedContent" />
<add key="Umbraco.ModelsBuilder.LanguageVersion" value="CSharp7" />
<add key="Umbraco.ModelsBuilder.ModelsDirectory" value="~/../Core/Model/PublishedContent/Generated/" />
<add key="Umbraco.ModelsBuilder.AcceptUnsafeModelsDirectory" value="true" />
```

Visual Studio Extension is installed and configured:
![image](https://user-images.githubusercontent.com/7048578/64611335-808f2080-d3d1-11e9-9843-f913a30d1ff1.png)

![image](https://user-images.githubusercontent.com/7048578/64611296-69e8c980-d3d1-11e9-8103-3883def5433c.png)


This happens when "run custom tool" is clicked:
![image](https://user-images.githubusercontent.com/7048578/64611610-26428f80-d3d2-11e9-9e4f-ffae09bc62da.png)

![image](https://user-images.githubusercontent.com/7048578/64611231-458ced00-d3d1-11e9-8407-cd6681994e3c.png)

**Comment by zpqrtbnk** [comment]
Please see [this blog post](https://www.zpqrtbnk.net/posts/models-builder-extension/) - the custom tool is deprecated and replaced by the extension, which does not work the same

**Comment by croban** [comment]
That helps thank you!
