### ISSUE TITLE
Compositions makes trouble

### ISSUE THREAD

**Issue by jesperordrup** [zpqrtbnk/Zbu.ModelsBuilder#33]
Im using Umb 7.21 and latest zbu.Modelsbuilder. Ive added a composition ("Pages") to my document type "TextPage". 

It seems that it breaks TextPage as it cant find IPages.

As a result only the other Doctypes work.

Modelsbuilder is setup to build to AppCode. I'm building using Umbraco Dashboard. 

The project is a "Website project" which is set not to build in VS so this should be the same as if it was running on any host right?

Any clues?

**Comment by zpqrtbnk** [comment]
So both TextPage and Pages are content types, and Pages is added to TextPage, right? Then, TextPage should implement an IPages interface (compositions are implemented as interfaces) and that interface should be generated. Let me test...

**Comment by zpqrtbnk** [comment]
Just created content types Test1 and Test2, both at root and without properties. Added Test1 to Test2. Here's what I have in test1.generated.cs:
```
	// Mixin content Type 3084 with alias "Test1"
	/// <summary>test1</summary>
	public partial interface ITest1 : IPublishedContent
	{
	}

	/// <summary>test1</summary>
	[PublishedContentModel("Test1")]
	public partial class Test1 : PublishedContentModel, ITest1
	{
```
And in test2.generated.cs:
```
	/// <summary>test2</summary>
	[PublishedContentModel("Test2")]
	public partial class Test2 : PublishedContentModel, ITest1
	{
```
And the solution builds. That's using the VS extension but it should not make a diff. Can you show me how you pages & textpage generated files look like?

**Comment by jesperordrup** [comment]
Mine look somewhat the same:

https://dl.dropboxusercontent.com/u/572995/zbu.archive.zip

**Comment by zpqrtbnk** [comment]
If you have
```
	/// <summary>Textpage</summary>
	[PublishedContentModel("Textpage")]
	public partial class Textpage : PublishedContentModel, IPages
	{
```
and
```
	// Mixin content Type 1047 with alias "Pages"
	/// <summary>Pages</summary>
	public partial interface IPages : IPublishedContent
	{
```
How would that break? What error are you seeing?

**Comment by jesperordrup** [comment]
![zbu in visual](https://cloud.githubusercontent.com/assets/3120151/5875457/967c610e-a30d-11e4-8dce-67045cde826e.png)

heres a VS screenshot

**Comment by zpqrtbnk** [comment]
Have you added the Pages.generated.cs file to the solution? This is strange.

**Comment by jesperordrup** [comment]
Its auto added as its a "Website"  (File, open Web Site ...) not a Web Application Project.

I could suspect it to be the reason but then it wouldnt work if generated on my hosting?

**Comment by zpqrtbnk** [comment]
Weird. What happens when you open the file in VS?

**Comment by jesperordrup** [comment]
Im not sure what you mean. I can open all the generated files. 

The TextPage file makes the above error.
The Pages file makes no error.

But none of them works.

New finding: copying all generated files to App_Code makes everything work

**Comment by jesperordrup** [comment]
Btw. is it possible to configure this to copy all generated files to App_Code?

**Comment by zpqrtbnk** [comment]
Ahhhhh of course, the files are generated in App_Data, right? So you have EnableAppCodeModels set to true in the config, right? Then there should be a something.models file in App_Code and that file should be touched when you generate the models. I think I understand the confusion here:

EnableAppCodeModels generates models in App_Data and then creates a single something.models in App_Code so that the build manager loads all the models file at once. But that's for the ASP.NET build manager and VS will not see the files. Hence the confusion.

If you want them in VS then you'll have to use EnableAppDataModels (they won't be loaded by the build manager as we won't generate the something.models file) and then manually include the files in the VS solution.

Looks like what you want is "plain App_Code files" ie that the files are generated straight into App_Code - this is something I haven't enabled at the moment, because writing files to App_Code restarts the app... while you are writing. So we need to figure out how to delay that restart (that's possible I think) while we write all the files.

Making more sense?

**Comment by jesperordrup** [comment]
App_data, right!
EnableAppCodeModels = true, right!

I'll try EnableAppDataModels (and disable EnableAppCodeModels i guess). I guess I then have to copy them manually to the App_Code folder.

yes - direct app_code will work everywhere.

**Comment by zpqrtbnk** [comment]
Direct app_code would be nice provided that I find a way to suspend app restart while I write the files... OK, closing the question!

**Comment by jesperordrup** [comment]
Sound great. Yes the EnableDirectAppCodeModels mode is missing :dart:
