### ISSUE TITLE
Textarea properties are returning as objects instead of strings

### ISSUE THREAD

**Issue by naepalm** [zpqrtbnk/Zbu.ModelsBuilder#36]
While this isn't generally a problem as I can override the property, I'm using the textarea in a component DocType, which means the interface is spitting out an object instead of a string which makes overriding it so much more annoying...

**Comment by zpqrtbnk** [comment]
This is because the TextArea doctype does not have a property converter declaring that it returns a string (or an IHtmlString) - so we don't know what's the type, so it's object. Core should probably embed a builtin converter for the TextArea doctype, but as long as it does not, just create your own and rebuild your models.
This would apply to any type that is exposed as object.
Making sense?

**Comment by naepalm** [comment]
Hi Stephen - yeah, that makes perfect sense. I understand. I guess the part I'm struggling with is that when using a component DocType, it creates an interface so doing an override is more complicated (I basically end up with 2 items in my model and then I have to ignore the object one and only call the string). But if that's what Umbraco returns, that's what we'll have to do!

**Comment by zpqrtbnk** [comment]
"ignore the object one and only call the string": you should not have the object one anymore. if you create a property value converter for the datatype, and that converter specifies that it returns strings, then the "object" property should be replaced by a "string" property - should not have both.

**Comment by naepalm** [comment]
Hi Stephen, when I ignore a property on a Component doctype, the property gets ignored, but the interface item remains, so I still have to implement it...

**Comment by zpqrtbnk** [comment]
Interesting... do you want that property ignored on _everything_ implementing the interface? Because then you might want to try to ignore it on the composition type itself. Should work, else it's a bug.

Otherwise, I see what you mean... you don't want the property but you're inheriting an interface that requires you to have that property... nothing much we can do.

**Comment by naepalm** [comment]
Yeah, I actually tried to ignore the property on the component type and add my own, but it was still forcing the interface to implement. Do you want me to submit a separate issue for a bug for that?

**Comment by zpqrtbnk** [comment]
Could you? Just create an issue about "ignoring properties on composition types" or something. Thanks!

**Comment by naepalm** [comment]
Done! Thanks so much for your responses and walking me through my questions :)

**Comment by zpqrtbnk** [comment]
Great.
