### ISSUE TITLE
return Image model not string gives me null

### ISSUE THREAD

**Issue by Lechus** [zpqrtbnk/Zbu.ModelsBuilder#37]
Hi,

I have models generated. I amend MediaPicker property from string to Image (auto-generated model), but it gives me null.
```
        [ImplementPropertyType("newsThumbnail")]
        public Image NewsThumbnail
        {
            get { return this.GetPropertyValue<Image>("newsThumbnail"); }
        }
```
As seen here: https://github.com/zpqrtbnk/Zbu.ModelsBuilder/issues/13
this technique is used with Grid and it works.
Is this not working with media picker or am I missing something?

**Comment by zpqrtbnk** [comment]
If you "just" amend the property so it's an image and not a string... it probably won't work because GetPropertyValue("whatever") is going to return a string anyway. If you want it to be an Image object you have to have a property value converter declared for that data type, that does return an image.

**Comment by zpqrtbnk** [comment]
Does that answer your question, and is it OK to close it?

**Comment by jbreuer** [comment]
You might want to look at the property editor convertor I wrote for the Hybrid Framework. In that version it works: https://github.com/jbreuer/Hybrid-Framework-for-Umbraco-v7-Best-Practises/blob/master/Umbraco.Extensions/PropertyConverters/MultipleMediaPickerConverter.cs

**Comment by Lechus** [comment]
@zpqrtbnk Yes, thank you.
@jbreuer Thanks, I have found it.
