### ISSUE TITLE
Override interface properties

### ISSUE THREAD

**Issue by jbreuer** [zpqrtbnk/Zbu.ModelsBuilder#40]
If you use the ImplementPropertyType attribute on a partial class the property disappears on the generated partial class because you're writing your own implementation. You can even let your own implementation return a different type.

For the generated interfaces this is currently not supported. I would like to change the type of an interface property that is generated from a composition.

**Comment by jbreuer** [comment]
I want to override the interface property so it can return a different type on a base class. See #41.

**Comment by zpqrtbnk** [comment]
At the moment attributes on a partial interface are ignored. In fact the interface is just the "interface view" of the underlying type. In other word, you have a type MyType, and because it's used in a composition we also generate interface IMyType. I tend to think that it's OK do ignore all attributes on the interface, because everything should be done on the type itself.

At the moment, [RenamePropertyType] applied to the type, will rename the property in the interface. However, [ImplementPropertyType] on a type's property will NOT change the property in the interface, and that's definitively a bug. Going to fix this, and then the proper way to achieve what you want would be to change the type property (and it would be mirrored in the interface).

Making sense?

**Comment by zpqrtbnk** [comment]
More about it. ```ImplementPropertyType``` should be used on the type, not the interface. In fact attributes on the interface are ignored. So you define a custom _implementation_ of the property, on the type. Then... it would be good if we could somehow derive the proper interface declaration for the property -- but I think this is going to be error-prone at best. Sooo what I propose is, once you ```ImplementPropertyType``` on a property on the type, it's not generated in the interface, and you _also_ have to manually write the declaration in a partial interface.

This _also_ means that the property needs to be manually implemented in any type that uses the composition type, because we cannot really figure out how to implement it in a reliable way (of course we could try to duplicate the implementation that you provide... but that's not always going to work...).

Thoughts?

**Comment by jbreuer** [comment]
How would this work when I want to use ImplementPropertyType on a base class that has the interface? Like I said in #41.

**Comment by zpqrtbnk** [comment]
Say you have that type, Something, that's used in compositions UsingType1 and UsingType2. And Something has a property SomeProp that is an integer. By default, we would generate interface ISomething (defining int SomeProp), class Something (implementing int SomeProp), and then classes UsingType1 and UsingType2 (both declaring they implement ISomething, and actually implementing int SomeProp).

If I understand correctly you want SomeProp to, say, return a string instead of an integer. Initial idea was to do it on a partial interface, but we don't want to support attributes on interfaces... they have to be on the type itself, so you'd do...
```
public partial class Something
{
  [ImplementPropertyType("someProp")]
  public string SomeProp { get { ... } }
}
```
Because you implement the property by yourself, we don't generate it in the interface anymore, so you'd also need to do:
```
public partial interface ISomething
{
  string SomeProp { get; }
}
```
And because you implement the property by yourself, we don't generate it in UsingType1 or UsingType2 anymore. So you'd have to do:
```
public partial class UsingType1
{
  [ImplementPropertyType("someProp")]
  public string SomeProp { get { ... } }
}
```
And also in UsingType2. Assuming you have UsingType1...UsingType99 and you don't want to write the above code 99 times... you may want to write a base class looking like:
```
public class SomeProbBase : PublishedContentModel
{
  public SomeProbBase(IPublishedContent content) : base(content) {}

  [ImplementPropertyType("someProp")]
  public string SomeProp { get { ... } }
}
```
And then...
```
public partial class UsingType1 : SomeProbBase {}
```
Though you still have to repeat that line 99 times... Now it's obvious what you want, right? You want me to copy your implementation of that property over to each of the 99 classes automatically. Correct?

I have no idea if it can be done. Looking into it.

**Comment by jbreuer** [comment]
The above is already good. Implementing that line 99 times isn't a problem because most of the time the classes that I'm working with also need to override some other properties with ImplementPropertyType so they already exist. 

So I think this will work :-).

**Comment by zpqrtbnk** [comment]
Then it should work as of 2.1.0 in its current state. TBH I think that's better because trying to "cut and paste" your property from the original type to all the derived types... might be possible... but smells. Fine then, 2.1 should be out soon.

**Comment by jbreuer** [comment]
With Umbraco 7.4 everything is a composition so the above situation will happen a lot more. Should Umbraco really stop supporting base document types?
