### ISSUE TITLE
Serializing models 

### ISSUE THREAD

**Issue by qz2rg4** [zpqrtbnk/Zbu.ModelsBuilder#46]
Hi 

I'm trying to serialize a model to be used in angular.

Unfortunately I get a "Self referencing loop detected" error 

```
    var _home = Umbraco.Content(id);
    Home hhh = new Home(_home);
     JsonSerializerSettings jss = new JsonSerializerSettings();
     jss.Formatting = Newtonsoft.Json.Formatting.Indented;
     jss.NullValueHandling = NullValueHandling.Ignore;
     jss.StringEscapeHandling = StringEscapeHandling.EscapeNonAscii;
     jss.TypeNameHandling = TypeNameHandling.Objects;
     jss.ReferenceLoopHandling = ReferenceLoopHandling.Error; //  if I change this to ignore or serilize I get a stack overflow.
    return JsonConvert.SerializeObject (hhh,jss);
```

Am I going about this the correct way or should I be serializing some other way 

Thanks

**Comment by zpqrtbnk** [comment]
What is "Home" exactly? In addition... models have references to their children & parents so it may very well be that serializing a model tries to serialize the entire content tree... We'd probably need some attributes on models (that can be done, need to think about how) to restrict what's serialized and what's not.

**Comment by qz2rg4** [comment]
Hi 

Thanks again for your reply and I apologize for my ambiguity.

"Home" is a simple document type with no children but it is in the first level of the content tree with the root as a parent with quite a few descendants. Since my site has allot of document types it would have been an enormous time saver if I could use your generated models to serialize. 

Hopefully there is a simple solution 

Thanks again

**Comment by zpqrtbnk** [comment]
Thinking about it... I'm not sure you can serialize a model in the current state. A model implements IPublishedContent so you'd need to be able to serialize an IPublishedContent, which probably fails because of the tree-related properties (parent, children...) which probably in the end cause you to serialiez the entire tree.

So it's more of a general Umbraco question - which I think can be solved by using a custom [IContractResolver](http://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_Serialization_IContractResolver.htm) during serialization. Will try and see if I can create one.

**Comment by zpqrtbnk** [comment]
Note to self: probably want to look at [this code](https://github.com/joeriks/Tapas/blob/master/Tapas.ContentHost/PublishedNodeSerializer.cs)...
