### ISSUE TITLE
Error generating models when a solution file contains solution folders

### ISSUE THREAD

**Issue by danlister** [zpqrtbnk/Zbu.ModelsBuilder#49]
After upgrading to v2.1.2 from v2.1.1, the ModelsBuilder VSIX is now unable to generate models when a solution file contains solution folders. After looking at the code, I can see that the way projects are iterated through has changed. The following [line](https://github.com/zpqrtbnk/Zbu.ModelsBuilder/blob/master/Zbu.ModelsBuilder.CustomTool/VisualStudio/VisualStudioHelper.cs#L42), specifically the reference to `dte.Solution.Projects`, loops through every kind of project file. This includes solution folders.

    var vsProject = dte.Solution.Projects
        .Cast<EnvDTE.Project>()
        .Select(ToHierarchy)
        .Cast<IVsProject>()
        .FirstOrDefault(x =>
        {
            int iFound;
            x.IsDocumentInProject(inputFilePath, out iFound, pdwPriority, out itemId);
            return iFound != 0 && itemId != 0;
        });

The exception actually occurs on the following [line](https://github.com/zpqrtbnk/Zbu.ModelsBuilder/blob/master/Zbu.ModelsBuilder.CustomTool/VisualStudio/VisualStudioHelper.cs#L100), as when selecting each project via the `ToHierarchy()` method, solution folders have no file name.

    using (var projectReader = XmlReader.Create(project.FileName))

A couple of fixes could be applied. The code could either select projects that do not match the solution folder type guid or a defensive code check could be added to `ToHierarchy()` to make sure we have something within the `FileName` property.

**Comment by zpqrtbnk** [comment]
Have merged the PR, and will release a new version in a few days.
Excellent work & MANY THANKS!

**Comment by danlister** [comment]
@zpqrtbnk No problem at all. Thanks for creating an awesome package :)

**Comment by Mesomorf** [comment]
Hi. It seems like I still have this problem.
I have installed the following
1) Umbraco ModelsBuilder Custom Tool v.2.1.3.43 in VS.
2) Zbu.ModelsBuilder.AspNet v.2.1.3-beta001
3) Zbu.ModelsBuilder v.2.1.3-beta001

If the assembly where i'm using the Builder.cs is inside a solution folder, the builder does not work (
ZbuModelsBuilder failed to generate code: Exception: Panic: source file not found in any project.).

If I move the assembly outside the solution folder every thing works fine.

**Comment by danlister** [comment]
Hey @Mesomorf. The extension requires a project file in order to build your models correctly. Is there a reason why your Builder.cs class lives in a Solution Folder? How would you have previously used your generated models if they did not reside within a compilable project? Thanks, Dan.

**Comment by Mesomorf** [comment]
Hi danlister

Maybe I haven't clean how my solution structure is.

+ Solution 
  + Solution folder
    + Project (with umbraco core + modelsbuilder core + builder.cs + other umbraco extensions)
  + Project (with umbraco + modelsbuilder aspnet)

in this solution structure does the builder not work

+ Solution 
  + Project (with builder.cs + umbraco core + modelsbuilder core)
  + Project (with umbraco + modelsbuilder aspnet)

but in this structure it works.

**Comment by zpqrtbnk** [comment]
Are we talking about *Windows* filesystem folder, ie real folders that you can see in the file explorer, or *Visual Studio* folders, ie the structure you see in the solution explorer? Also - any chance you can share with me (email) a ZIP of the entire structure that is not working?

**Comment by Mesomorf** [comment]
It's the structure in  VS solution explorer

**Comment by Mesomorf** [comment]
Sure I can send you a VS solution that generate this error.

But where do I send it to?

 

Fra: Stephan [mailto:notifications@github.com] 
Sendt: 13. juni 2015 18:55
Til: zpqrtbnk/Zbu.ModelsBuilder
Cc: Mesomorf
Emne: Re: [Zbu.ModelsBuilder] Error generating models when a solution file contains solution folders (#49)

 

Are we talking about Windows filesystem folder, ie real folders that you can see in the file explorer, or Visual Studio folders, ie the structure you see in the solution explorer? Also - any chance you can share with me (email) a ZIP of the entire structure that is not working?

**Comment by zpqrtbnk** [comment]
OK, I have downloaded the solution. Now I see: you have some projects *within* a Visual Studio "Solution Folder". Unfortunately, that is not supported at the moment.

Some background: when the custom tool runs, it needs to go through the entire solution to locate the Visual Studio "internal" object corresponding to the file that supports the custom tool (eg builder.cs or generator.cs). Originally, we would look at any root project in the solution, but that would fail with some types of projects such as web apps, and... solution folders. So for the time being, these two types of projects are skipped/ignored.

In order to deal with your solution, the processing code needs to be refactored. I have created [this issue](https://github.com/zpqrtbnk/Zbu.ModelsBuilder/issues/54) to take care of it when possible. And of course... the code is open, so if anyone feels like having a look at it... that'd be great!

**Comment by Mesomorf** [comment]
Thanks for the help.

 

 

 

Fra: Stephan [mailto:notifications@github.com] 
Sendt: 14. juni 2015 16:47
Til: zpqrtbnk/Zbu.ModelsBuilder
Cc: Mesomorf
Emne: Re: [Zbu.ModelsBuilder] Error generating models when a solution file contains solution folders (#49)

 

OK, I have downloaded the solution. Now I see: you have some projects within a Visual Studio "Solution Folder". Unfortunately, that is not supported at the moment.

Some background: when the custom tool runs, it needs to go through the entire solution to locate the Visual Studio "internal" object corresponding to the file that supports the custom tool (eg builder.cs or generator.cs). Originally, we would look at any root project in the solution, but that would fail with some types of projects such as web apps, and... solution folders. So for the time being, these two types of projects are skipped/ignored.

In order to deal with your solution, the processing code needs to be refactored. I have created this issue <https://github.com/zpqrtbnk/Zbu.ModelsBuilder/issues/54>  to take care of it when possible. And of course... the code is open, so if anyone feels like having a look at it... that'd be great!

**Comment by zpqrtbnk** [comment]
beta008 is now out and should fix most of these issues including projects in solution folders. would be great if you all could test. thanks!

**Comment by Mesomorf** [comment]
Sure I’ll test it. Is there a version on nuGet or do I get the source code?

 

Fra: Stephan [mailto:notifications@github.com] 
Sendt: 18. juni 2015 14:16
Til: zpqrtbnk/Zbu.ModelsBuilder
Cc: Mesomorf
Emne: Re: [Zbu.ModelsBuilder] Error generating models when a solution file contains solution folders (#49)

 

beta008 is now out and should fix most of these issues including projects in solution folders. would be great if you all could test. thanks!

**Comment by zpqrtbnk** [comment]
beta008 does not change the site-hosted part, only the VSIX extension, which you can download on the [release page](https://github.com/zpqrtbnk/Zbu.ModelsBuilder/releases/tag/2.1.3-beta008).

**Comment by Mesomorf** [comment]
I’t seem like it have solved my problem. I have been moving my project around in the solution structure and the models are generated.

 

Fra: Stephan [mailto:notifications@github.com] 
Sendt: 19. juni 2015 08:12
Til: zpqrtbnk/Zbu.ModelsBuilder
Cc: Mesomorf
Emne: Re: [Zbu.ModelsBuilder] Error generating models when a solution file contains solution folders (#49)

 

beta008 does not change the site-hosted part, only the VSIX extension, which you can download on the release page <https://github.com/zpqrtbnk/Zbu.ModelsBuilder/releases/tag/2.1.3-beta008> .
