### ISSUE TITLE
Cannot rebuild the VSIX package

### ISSUE THREAD

**Issue by zpqrtbnk** [zpqrtbnk/Zbu.ModelsBuilder#52]
Getting error VSSDK1031 - "Extension '<myGuid>' could not be found. Please make sure the extension has been installed." Not sure anything has changed in the project file, really. Can fix by editing the project propertiex, VSIX tab, and unchecking "Deploy VSIX content to experimental instance for debugging". But?

**Comment by zpqrtbnk** [comment]
Read [this MSDN post](https://social.msdn.microsoft.com/Forums/vstudio/en-US/b9060eae-534c-4537-aaaa-ab3eceae5c57/deploy-to-experimental-instance-deploys-to-wrong-location-after-upgrade-to-vs2013?forum=vsx) which says:

> I had the same issue. No suggested solution worked. The problem was: somehow, the experimental instance refused to install the current extension version. Hence the error message which seems to come from a check task during the build.

> The "solution" for me: simply increase the version number of the extension. This causes VS to recognize it as 'new' and allows the install.... Took me 2h to find out.

Need to try it.

**Comment by zpqrtbnk** [comment]
Tried to bump the minor version (2.1.3.44 to 2.1.3.46) in the manifest file - does not work.

**Comment by AmadeusW** [comment]
This issue came up in search results when I had the same problem. [I blogged](http://blog.comealive.io/Vsix-extension-could-not-be-found/) about a solution that worked for me: reset the `/rootsuffix exp` command line argument in `Zbu.ModelsBuilder.CustomTool` properties, build the solution, restore the argument and build again. Let me know how it went!

**Comment by zpqrtbnk** [comment]
Thanks for the suggestion. Tried to build again today and somehow, it works.
Weird.

**Comment by zpqrtbnk** [comment]
Having the same issue again, with Visual Studio 2015.

Looked at @AmadeusW blog post, unfortunately my solution does _not_ have anything in command line arguments that I can remove. So the main solution would not work. So I went on trying the other options, including removing the extension from the main VS instance, and doing (which essentially re-creates the experimental instance):
```
cd "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VSSDK\VisualStudioIntegration\Tools\Bin"
CreateExpInstance.exe /Reset /VSInstance=14.0 /RootSuffix=Exp
```
Alas, nothing seems to work. 

Next I decided to compare my VSIX project against a fresh project. In my project options, Debug start action was set to "start project" and not in the fresh project. So I changed mine to align with the fresh project, ie "start external program" with option `/rootsuffix Exp`.

Fails.

Read [this issue](https://github.com/Microsoft/VSProjectSystem/issues/74) and tried to manually start the exp instance. Ie, exit all instances of Visual Studio, do the reset as explained above, then

```
cd "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE"
devenv.exe /rootsuffix exp
```

Works!

**Comment by AmadeusW** [comment]
So did your build process create the .vsix and deploy it to the experimental instance only after you manually launched and closed experimental Visual Studio?

**Comment by zpqrtbnk** [comment]
Correct - it worked only after I manually started experimental Visual Studio - even resetting, deleting & recreating the experimental VS was not enough

**Comment by AmadeusW** [comment]
Thank you. I will update the blog post!

**Comment by tahaipek** [comment]
I solved this problem. Thanks for response @zpqrtbnk
There is an easier solution. Delete this folder and VS will be recreated with default settings. _C:\Users\**User**\AppData\Local\Microsoft\VisualStudio\14.0Exp_

**Comment by ChristopherHaws** [comment]
It seems like the issue is that the assembly's version (not the extension version in the manifest file) is not being incremented. I was having this problem when the assembly version was set to `[assembly: AssemblyVersion("1.0.0.0")]` or did not exist. Changing it to `[assembly: AssemblyVersion("1.0.*")]` solved the issue for me.

**Comment by claudiuconstantin** [comment]
Increasing the version number of the extension worked for me.

**Comment by zpqrtbnk** [comment]
Weird - I tried in the past to go from eg 1.0.0.0 to 1.0.0.1 without success... but IIC you are going from 1.0.0.0 to 1.0.1.0 - wondering if that makes a difference?

**Comment by janvanderhaegen** [comment]
My version of this issue was resolved after deleting the 14.Exp folder as @tahaipek suggests, then manually starting devenv.exe with /rootsuffix Exp arguments. Visual Studio opened, I went to Tools > Extensions and Updates, and the "Composing MEF graph" dialog popped up. 
After that, I could close the exp VS and all was well again.
