### ISSUE TITLE
Configure location of generated files

### ISSUE THREAD

**Issue by zpqrtbnk** [zpqrtbnk/Zbu.ModelsBuilder#74]
Cont. discussion from https://github.com/zpqrtbnk/Zbu.ModelsBuilder/issues/73

**Comment by lars-erik** [comment]
Currently we put all our models in ~/Models/DocumentTypes, so that would be within the web.
But of course this is for dev mode, since the point of doing this is having something like "Domain Entities" and MVC Models we can unit-test and do logic with, and obviously always compile manually. Having them in App_Code kind of kills all of the more "hardcore" developer solution setups.

But I've had requests to support outside web paths for codegen, so I suppose it's something people would want to do. For instance putting the classes in a "common assembly" with less dependencies. (I guess Umbraco.Core must be referenced in any case)

**Comment by zpqrtbnk** [comment]
Supporting a ~/Models/DocumentTypes of some sort should be easy. The whole point of generating them in ~/App_Data/Models was for the same reason: avoid the app restart that happens when generating in App_Code. Will look into how we can make it an option.

Going outside the web paths... I guess it would work provided that the site has permissions to write in the target directory. So maybe there would be a second option "EnableWritingOutsideOfWebPathsAndYesIUnderstandTheRisks" of some sort.

**Comment by lars-erik** [comment]
Hehe, yeah, sounds good. Might iterate a bit on the name.

**Comment by lars-erik** [comment]
Is solved in #94 btw. :)

**Comment by zpqrtbnk** [comment]
Release in 3.0.5!

**Comment by lars-erik** [comment]
\o/

All that's left for me to be a very happy dev is opening up the writer. ;)

**Comment by lars-erik** [comment]
Also love the hidden unsafe external dir. option. Will have to test soon.
