### ISSUE TITLE
Generated Property Names dont use the PropertyName rather the alias

### ISSUE THREAD

**Issue by djomen** [zpqrtbnk/Zbu.ModelsBuilder#9]
I am guess this is by design to prevent iffy characters in the Property Name?

Is the only way around this to create the directives on the model or could there be a setting to use the PropertyName instead of the alias during the generation?

**Comment by zpqrtbnk** [comment]
Won't do. Low priority. Plus, if we derive from names, it will not be *exactly* the name (because of iffy chars) and so you have to look at the code to figure out what's the name in the end. So we keep using aliases. And if someone wants a different name, it's always possible to rename content and property models.
